#!/usr/bin/env bash

dir="$HOME/Pictures/Screenshots"
mkdir -p "$dir"

file="$dir/$(date +%Y-%m-%d_%H-%M-%S).png"

grim -g "$(slurp)" - | tee "$file" | wl-copy --type image/png

action=$(notify-send \
  -i "$file" \
  -a "Screenshot" \
  -A default="Open" \
  "Screenshot taken" \
  "$(basename "$file") saved and copied to clipboard")

if [[ "$action" == "default" ]]; then
  xdg-open "$file"
fi